const Products = [
  {
    id: 1,
    name: 'Combo 1',
    category: 'Combo',
    img: 'https://www.freeiconspng.com/uploads/fast-food-png-most-popular-fast-food-snacks-in-your-area-and-most--3.png',
    price: 30.35,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 2,
    name: 'Combo 2',
    category: 'Combo',
    img: 'https://www.freeiconspng.com/uploads/fast-food-png-most-popular-fast-food-snacks-in-your-area-and-most--3.png',
    price: 30.35,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 3,
    name: 'Combo 3',
    category: 'Combo',
    img: 'https://www.freeiconspng.com/uploads/fast-food-png-most-popular-fast-food-snacks-in-your-area-and-most--3.png',
    price: 30.35,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 4,
    name: 'Combo 4',
    category: 'Combo',
    img: 'https://www.freeiconspng.com/uploads/fast-food-png-most-popular-fast-food-snacks-in-your-area-and-most--3.png',
    price: 30.35,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 5,
    name: 'Acompanhamento 1',
    category: 'Acompanhamento',
    img: 'https://www.freepnglogos.com/uploads/fried-chicken-png/home-texas-chicken-fried-chicken-oman-26.png',
    price: 25,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 6,
    name: 'Acompanhamento 2',
    category: 'Acompanhamento',
    img: 'https://www.freepnglogos.com/uploads/fried-chicken-png/home-texas-chicken-fried-chicken-oman-26.png',
    price: 25,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 7,
    name: 'Acompanhamento 3',
    category: 'Acompanhamento',
    img: 'https://www.freepnglogos.com/uploads/fried-chicken-png/home-texas-chicken-fried-chicken-oman-26.png',
    price: 25,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 8,
    name: 'Acompanhamento 4',
    category: 'Acompanhamento',
    img: 'https://www.freepnglogos.com/uploads/fried-chicken-png/home-texas-chicken-fried-chicken-oman-26.png',
    price: 25,
    description: 'Hambúrguer, refrigerante e batata-frita',
  },
  {
    id: 9,
    name: 'Bebida 1',
    category: 'Bebida',
    img: 'https://www.freeiconspng.com/uploads/cocktail-coca-cola-png-image-14.png',
    price: 10,
    description: 'líquido',
  },
  {
    id: 10,
    name: 'Bebida 2',
    category: 'Bebida',
    img: 'https://www.freeiconspng.com/uploads/cocktail-coca-cola-png-image-14.png',
    price: 10,
    description: 'líquido',
  },
  {
    id: 11,
    name: 'Sobremesa 1',
    category: 'Sobremesa',
    img: 'https://pngimg.com/uploads/cake/cake_PNG13097.png',
    price: 15,
    description: 'Doce',
  },
  {
    id: 12,
    name: 'Sobremesa 2',
    category: 'Sobremesa',
    img: 'https://pngimg.com/uploads/cake/cake_PNG13097.png',
    price: 15,
    description: 'Doce',
  },
];

export default Products;
